/*
 * Lite API
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.RatesBookPostRequestGuestInfo;
import org.openapitools.client.model.RatesBookPostRequestPayment;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RatesBookPostRequest
 */
public class RatesBookPostRequestTest {
    private final RatesBookPostRequest model = new RatesBookPostRequest();

    /**
     * Model tests for RatesBookPostRequest
     */
    @Test
    public void testRatesBookPostRequest() {
        // TODO: test RatesBookPostRequest
    }

    /**
     * Test the property 'prebookId'
     */
    @Test
    public void prebookIdTest() {
        // TODO: test prebookId
    }

    /**
     * Test the property 'guestInfo'
     */
    @Test
    public void guestInfoTest() {
        // TODO: test guestInfo
    }

    /**
     * Test the property 'payment'
     */
    @Test
    public void paymentTest() {
        // TODO: test payment
    }

}
