/*
 * Lite API
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RatesBookPostRequestGuestInfo
 */
public class RatesBookPostRequestGuestInfoTest {
    private final RatesBookPostRequestGuestInfo model = new RatesBookPostRequestGuestInfo();

    /**
     * Model tests for RatesBookPostRequestGuestInfo
     */
    @Test
    public void testRatesBookPostRequestGuestInfo() {
        // TODO: test RatesBookPostRequestGuestInfo
    }

    /**
     * Test the property 'guestFirstName'
     */
    @Test
    public void guestFirstNameTest() {
        // TODO: test guestFirstName
    }

    /**
     * Test the property 'guestLastName'
     */
    @Test
    public void guestLastNameTest() {
        // TODO: test guestLastName
    }

    /**
     * Test the property 'guestEmail'
     */
    @Test
    public void guestEmailTest() {
        // TODO: test guestEmail
    }

}
