/*
 * Lite API
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BookingManagementApi
 */
@Disabled
public class BookingManagementApiTest {

    private final BookingManagementApi api = new BookingManagementApi();

    /**
     * Booking retrieve
     *
     * The API returns the status and the details for the a specific booking Id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingsBookingIdGetTest() throws ApiException {
        Object bookingId = null;
        Object response = api.bookingsBookingIdGet(bookingId);
        // TODO: test validations
    }

    /**
     * Booking cancel
     *
     * &lt;!-- theme: danger --&gt; This API is used to request a cancellation of an existing confirmed booking. Cancellation policies and conditions will be used to determine the success of the cancellation. For example a booking with non-refundable (NRFN) tag or a booking with a cancellation policy that was requested past the cancellation date will not be able to cancel the confirmed booking.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingsBookingIdPutTest() throws ApiException {
        Object bookingId = null;
        Object response = api.bookingsBookingIdPut(bookingId);
        // TODO: test validations
    }

    /**
     * Booking list
     *
     * The API returns the list of booking Id&#39;s for a given guest Id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingsGetTest() throws ApiException {
        Object guestId = null;
        Object response = api.bookingsGet(guestId);
        // TODO: test validations
    }

}
